# Generated by Django 5.0 on 2023-12-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_riddle_alter_user_email_riddletoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
