# Generated by Django 5.0 on 2024-01-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="route_clustering_begins",
            field=models.BooleanField(default=False),
        ),
    ]
