# Generated by Django 5.0 on 2023-12-30 10:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('time_from_start', models.PositiveIntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('route', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='relation.route')),
            ],
        ),
    ]
