# Generated by Django 5.0 on 2024-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relation", "0005_cluster_remove_route_exceptional_route_exeptional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="cluster_label",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
