# Generated by Django 5.0 on 2024-01-26 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relation", "0006_cluster_cluster_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="exeptional",
            new_name="exceptional",
        ),
    ]
