# Generated by Django 5.0 on 2024-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relation", "0008_remove_cluster_cluster_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="centre_latitude_arrivee",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="centre_latitude_depart",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="centre_longitude_arrivee",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="centre_longitude_depart",
            field=models.FloatField(default=0.0),
        ),
    ]
