# Generated by Django 5.0 on 2024-02-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relation", "0009_alter_cluster_centre_latitude_arrivee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="representative",
            field=models.BooleanField(default=False),
        ),
    ]
